### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by mikekreeki** [mattn/ctrlp-launcher#2]
This looks like a handy plugin but I cannot get ctrlp-launcher to work. Looks like parsing issue to me.

![](https://dl.dropboxusercontent.com/u/6573004/Screenshot%202015-02-27%2020.06.05.png)
![](https://dl.dropboxusercontent.com/u/6573004/Screenshot%202015-02-27%2020.12.13.png)

It fails with this simple `~/.ctrlp-launcher`
````
Foo       !echo foo
```

Am I missing something?

**Comment by mattn** [comment]
I added check to the line is valid. You need to use TAB instead of SPACEs.

**Comment by mikekreeki** [comment]
Thanks! I forgot my vim converts tabs to spaces. Now it works properly.
